dashbuilder/dashbuilder

- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DisplayerSubtypeSelector.java
- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DisplayerTypeSelector.java
- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DisplayerTypeSelector.ui.xml
Adding some ids and css class names for selenium testing
> Ids4testing

- dashbuilder-client/dashbuilder-common-client/src/main/java/org/dashbuilder/common/client/validation/editors/DropDownImageListEditor.java
- dashbuilder-client/dashbuilder-widgets/src/main/java/org/dashbuilder/client/widgets/dataset/editor/widgets/editors/DataSetPreviewEditor.ui.xml
Added some DOM attributes to be able to find stuff for selenium testing.
Also migrated DataSetClientImages to ImageResource to reduce some boilerplate.
> Selenium stuff

- .gitignore
(cherry picked from commit 70672251fd62240ec5def7c35223c4c32b9884ae)
> added directory to ignore

- dashbuilder-backend/dashbuilder-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchMultiFieldsTest.java
Same fix already pushed to master.
> Fix for an ELS unit test due to the use of java8.

- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/model/SQLStatement.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/model/Select.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetDefTest.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLTableDataSetLookupTest.java
> DASHBUILDE-97: Allow columns alias in logical expressions

- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/model/SQLStatement.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/model/Select.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetDefTest.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLTableDataSetLookupTest.java
> DASHBUILDE-97: Allow columns alias in logical expressions (0.4.x)

- dashbuilder-backend/dashbuilder-services/pom.xml
- dashbuilder-bom/pom.xml
- dashbuilder-distros/pom.xml
- dashbuilder-distros/src/main/assembly/assembly-tomcat-7.xml
- dashbuilder-webapp/pom.xml
- pom.xml
Depends on:
https://github.com/errai/errai/pull/180
https://github.com/uberfire/uberfire/pull/400
> Upgrade IP BOM to 7.0.0.CR4 + related fixes

- dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/DisplayerDragComponent.java
API changes related to: https://github.com/uberfire/uberfire/pull/413
> UF-224: New Layout Editor

- dashbuilder-backend/dashbuilder-dataset-cdi/src/main/java/org/dashbuilder/Bootstrap.java
- dashbuilder-backend/dashbuilder-dataset-cdi/src/main/java/org/dashbuilder/dataprovider/DataSetProviderRegistryCDI.java
- dashbuilder-backend/dashbuilder-dataset-cdi/src/main/java/org/dashbuilder/dataset/DataSetDefDeployerCDI.java
- dashbuilder-backend/dashbuilder-dataset-cdi/src/main/java/org/dashbuilder/dataset/DataSetDefRegistryCDI.java
- dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/BootstrapTest.java
Fix + tests
@mbarkley Can you please verify?
> DASHBUILDE-151: DataSetDefRegistryCDI can be called before being initialized

- dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenter.java
- dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreen.java
- dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefWizardScreenTest.java
This PR updates the usage of PopUps in order to call the new PopUps API (that implements the MVP pattern using Errai UI).
See:
- https://issues.jboss.org/browse/GUVNOR-2431
- https://github.com/uberfire/uberfire/pull/443
> GUVNOR-2431: Redesign Copy, Save, Rename, Restore and Delete Popups (away from FormStylePopup)

- dashbuilder-client/dashbuilder-displayer-editor/pom.xml
- dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/DisplayerDragComponent.java
- dashbuilder-webapp/pom.xml
Depends on https://github.com/uberfire/uberfire/pull/459
> [UF-348] Apply UX design on new Layout Editor

- dashbuilder-client/dashbuilder-common-client/pom.xml
- dashbuilder-client/pom.xml
- dashbuilder-shared/dashbuilder-validations/pom.xml
- dashbuilder-webapp/pom.xml
- pom.xml
Needs:
droolsjbpm/droolsjbpm-build-bootstrap#250
errai/errai#184
uberfire/uberfire#461
> Upgrade to GWT 2.8.0-rc1

- dashbuilder-client/dashbuilder-widgets/src/main/java/org/dashbuilder/client/widgets/dataset/explorer/DataSetExplorerView.ui.xml
> Minor positioning and spacing fix for when no data set are available

- dashbuilder-deps/pom.xml
- pom.xml
> upgraded to jboss-ip-bom 6.0.8.Final

- dashbuilder-webapp/src/main/java/org/dashbuilder/client/perspectives/HomePerspective.html
- dashbuilder-webapp/src/main/java/org/dashbuilder/client/perspectives/HomePerspective.java
Depends on https://github.com/uberfire/uberfire/pull/581
> [UF-448] Upgrade Templated Perspectives to Errai UI

- dashbuilder-backend/dashbuilder-dataset-core/src/main/java/org/dashbuilder/dataset/IntervalBuilderDynamicDate.java
- dashbuilder-client/dashbuilder-dataset-client/src/main/java/org/dashbuilder/dataset/client/engine/ClientIntervalBuilderDynamicDate.java
- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/DataSetHandlerImpl.java
- dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/DisplayerCoordinatorTest.java
- dashbuilder-shared/dashbuilder-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/group/IntervalBuilder.java
- dashbuilder-shared/dashbuilder-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/group/IntervalBuilderDynamicLabel.java
- dashbuilder-shared/dashbuilder-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/group/IntervalBuilderFixedDate.java
Fix + test
@csadilek This fix is bounded to the next patch release (cut date Jan 2nd). tbh I do not know who else could review this. Would you mind please?
> DASHBUILDE-171: Filter not working for a displayer with empty intervals

- dashbuilder-webapp/src/main/java/org/dashbuilder/client/navbar/AppNavBar.html
- dashbuilder-webapp/src/main/java/org/dashbuilder/client/navbar/AppNavBar.java
- dashbuilder-webapp/src/main/java/org/dashbuilder/client/navbar/LogoNavBar.html
- dashbuilder-webapp/src/main/java/org/dashbuilder/client/navbar/LogoNavBar.java
- dashbuilder-webapp/src/main/java/org/dashbuilder/client/navbar/LogoWidgetView.java
Depends on https://github.com/uberfire/uberfire/pull/573
> [UF-443] - Header and Footer should support Errai UI

- scripts/release/DSL-scripts/DASHBUILDER_Release.sh
@dgutierr Sorry - had the Block Uppercase Key enabled
> DSL-script: fixed typo

- pom.xml
> Create project-sources archive during full build

- dashbuilder-shared/dashbuilder-dataset-api/src/main/java/org/dashbuilder/dataset/def/DataSetDef.java
- dashbuilder-shared/dashbuilder-dataset-api/src/test/java/org/dashbuilder/dataset/DataSetDefTest.java
Fix + test.
@wmedvede Can you approve please?
> DASHBUILDE-235 DataSetDef.equals() compares integers by reference

- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DateParameterEditorView.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/main/java/org/dashbuilder/renderer/client/selector/SelectorSliderDisplayer.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/main/java/org/dashbuilder/renderer/client/selector/SelectorSliderDisplayerView.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/test/java/org/dashbuilder/renderer/client/selector/SelectorCoordinatorTest.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/test/java/org/dashbuilder/renderer/client/selector/SelectorSliderDisplayerTest.java
Fixes + tests.
@romartin Can you merge please?
> DASHBUILDE-254: Slider selector fine tuning

- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/filter/DateParameterEditorView.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/main/java/org/dashbuilder/renderer/client/selector/SelectorSliderDisplayer.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/main/java/org/dashbuilder/renderer/client/selector/SelectorSliderDisplayerView.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/test/java/org/dashbuilder/renderer/client/selector/SelectorCoordinatorTest.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/test/java/org/dashbuilder/renderer/client/selector/SelectorSliderDisplayerTest.java
@romartin Can you merge please?
> DASHBUILDE-254: Slider selector fine tuning (0.9.x)

- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
- dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/DisplayerCoordinatorTest.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-google/src/main/java/org/dashbuilder/renderer/google/client/GoogleCategoriesDisplayerView.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-google/src/main/java/org/dashbuilder/renderer/google/client/GoogleDisplayer.java
Fix + tests.
@romartin Can you review & merge please?
> DASHBUILDE-258: Displayer filter labels sometimes cannot be closed (1.0.x)

- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
- dashbuilder-client/dashbuilder-displayer-client/src/test/java/org/dashbuilder/displayer/client/DisplayerCoordinatorTest.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-google/src/main/java/org/dashbuilder/renderer/google/client/GoogleCategoriesDisplayerView.java
- dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-google/src/main/java/org/dashbuilder/renderer/google/client/GoogleDisplayer.java
Fix + test.
@romartin Can you approve & merge please?
> DASHBUILDE-258: Displayer filter labels sometimes cannot be closed

- scripts/release/dashbuilder-createAndDeploy.sh
kie-soup (master)  has to be released (now) before dashbuilder - please merge this
> added sed change of kie-soup version

- dashbuilder-client/dashbuilder-cms-client/pom.xml
- dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/explorer/ContentExplorerScreen.java
- dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/screen/home/ContentManagerHomeScreen.java
- dashbuilder-client/dashbuilder-cms-client/src/main/java/org/dashbuilder/client/cms/widget/PerspectivesExplorer.java
- dashbuilder-client/dashbuilder-cms-client/src/test/java/org/dashbuilder/client/cms/screen/explorer/ContentExplorerScreenTest.java
- dashbuilder-client/dashbuilder-cms-client/src/test/java/org/dashbuilder/client/cms/widget/PerspectivesExplorerTest.java
- dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/plugin/PerspectivePluginManager.java
- dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/widget/editor/NavItemEditor.java
- dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/widget/editor/NavTreeEditor.java
- dashbuilder-client/dashbuilder-navigation-client/src/test/java/org/dashbuilder/client/navigation/plugin/PerspectivePluginManagerTest.java
- dashbuilder-client/dashbuilder-navigation-client/src/test/java/org/dashbuilder/client/navigation/widget/editor/NavItemEditorTest.java
- dashbuilder-client/dashbuilder-navigation-client/src/test/java/org/dashbuilder/client/navigation/widget/editor/NavTreeEditorTest.java
Fix + tests.
Depends on https://github.com/AppFormer/uberfire/pull/893
> CMS perspective fixes

- dashbuilder-client/dashbuilder-common-client/src/main/java/org/dashbuilder/common/client/editor/list/DropDownEditor.java
- dashbuilder-client/dashbuilder-common-client/src/test/java/org/dashbuilder/common/client/editor/list/DropDownEditorTest.java
Changes required by https://github.com/AppFormer/uberfire/pull/905
> AF-905: Errors while creating a page with the name of an existing screen

- dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/widget/editor/TargetPerspectiveEditor.java
- dashbuilder-client/dashbuilder-navigation-client/src/test/java/org/dashbuilder/client/navigation/widget/editor/TargetPerspectiveEditorTest.java
@kkufova Can you verify please?
> DASHBUILDE-263: [CMS perspective] Nav item edition shows null values in the group selector

- dashbuilder-bom/pom.xml
- dashbuilder-webapp/pom.xml
- pom.xml
This reverts commit 3cabbbd431d97a33033a6fd48d9c221e3943ca5e.
> upgraded jboss-ip-bom to 8.0.0.CR2

- dashbuilder-backend/dashbuilder-dataset-cdi/src/test/java/org/dashbuilder/dataset/DataSetSubsystemCDITest.java
- dashbuilder-backend/dashbuilder-dataset-core/src/main/java/org/dashbuilder/dataset/IntervalBuilderLocatorImpl.java
- dashbuilder-backend/dashbuilder-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetGroupTest.java
- dashbuilder-backend/dashbuilder-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchCommonTests.java
- dashbuilder-backend/dashbuilder-dataset-sql-tests/dashbuilder-dataset-sql-tests-db2/src/test/resources/testdb-db2.properties
- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/model/Column.java
- dashbuilder-backend/dashbuilder-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLTableDataSetLookupTest.java
- dashbuilder-client/dashbuilder-dataset-client/src/main/java/org/dashbuilder/dataset/client/engine/ClientIntervalBuilderLocator.java
- dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/widgets/DataSetLookupEditorView.java
- dashbuilder-shared/dashbuilder-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/group/IntervalBuilderDynamicLabel.java
@dgutierr here are the backports required for https://issues.jboss.org/browse/RHBPMS-5091
I haven't done anything here, just cherry picked them ;)
> [0.5.x] DASHBUILDE-156: Group by numeric fields as labels, DASHBUILDE-181: Error 'Column not found' when adding group by column

- dashbuilder-client/dashbuilder-dataset-editor/src/main/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenter.java
- dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenterTest.java
- dashbuilder-client/dashbuilder-dataset-editor/src/test/java/org/dashbuilder/dataset/editor/client/screens/DataSetDefEditorPresenterValidationTest.java
- dashbuilder-deps/pom.xml
https://issues.jboss.org/browse/AF-1079
These PRs change the service visibilities to protected for testing purposes. Not how I would like to do them, but the other option is to do even more refactoring and since this is an older branch, I don't think it is worth the risk.
https://github.com/AppFormer/uberfire-extensions/pull/324
https://github.com/dashbuilder/dashbuilder/pull/419
https://github.com/kiegroup/kie-wb-common/pull/1489
https://github.com/kiegroup/drools-wb/pull/825
https://github.com/kiegroup/jbpm-wb/pull/992
> [0.5.x] AF-1079 : Empty 'Validation errors' popup in Decision/Business Central
